### ISSUE TITLE
"selectedcontentcaches_dirty" is missing for ms sql server

### ISSUE THREAD

**Issue by mprins** [B3Partners/tailormap#2248]
### Version
Which version of flamingo do you use:  5.7.7

### Where and/or What

An error is logged while starting up when starting the viewer.

For some reason `selectedcontentcaches_dirty` is used twice (@mtoonen why?), for database revisions 9 and 40, but it is not available MS SQL Server, because it was not supported in the old days.

### Server log
<details><summary>relevant section of the server log:</summary>

```

2021-01-25 17:58:22 INFO  nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer.doInit(DatabaseSynchronizer.java:212) - Checking for need to update the database.
2021-01-25 17:58:22 INFO  nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer.doInit(DatabaseSynchronizer.java:227) - Current database version is: 39
2021-01-25 17:58:22 DEBUG nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer$ScriptWorker.execute(DatabaseSynchronizer.java:387) - Start looking for: /scripts/selectedcontentcaches_dirty.sql
2021-01-25 17:58:22 ERROR nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer$ScriptWorker.execute(DatabaseSynchronizer.java:409) - Error while executing script: selectedcontentcaches_dirty.sql
java.lang.Exception: Update script 'selectedcontentcaches_dirty.sql' nor 'microsoft_sql_server-selectedcontentcaches_dirty.sql' can be found
	at nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer$ScriptWorker.execute(DatabaseSynchronizer.java:394)
	at org.hibernate.impl.SessionImpl.doWork(SessionImpl.java:1997)
	at nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer.doInit(DatabaseSynchronizer.java:242)
	at nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer.init(DatabaseSynchronizer.java:449)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4902)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5211)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1727)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:288)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:459)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:408)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:288)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.sun.jmx.remote.security.MBeanServerAccessController.invoke(MBeanServerAccessController.java:468)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1408)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-01-25 17:58:22 INFO  nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer.doInit(DatabaseSynchronizer.java:244) - Database updates returned a error.
2021-01-25 17:58:22 INFO  nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer.doInit(DatabaseSynchronizer.java:269) - No updates done on database, maybe a error occured
2021-01-25 17:58:22 WARN  nl.b3p.viewer.util.databaseupdate.DatabaseSynchronizer.doInit(DatabaseSynchronizer.java:278) - Version of database is: 39 while the version must be: 40 Try to do the updates manualy


```

</details>

### What did you expect?

Should be able to upgrade the database from 39 to 40 on MS SQL Server.

### Reproduce
How can we reproduce this? 

  1.  MS SQL database with metedata version 39
  2. viewer 5.7.7 or later

**Comment by mprins** [comment]
caused by #1898
